### ISSUE TITLE
Failed to get server status. panic: collector has no descriptors

### ISSUE THREAD

**Issue by vicksiyi** [dcu/mongodb_exporter#129]
```
### Warning: the exporter is in beta/experimental state and field names are very
### likely to change in the future and features may change or get removed!
### See: https://github.com/percona/mongodb_exporter for updates
mongodb_exporter version: unknown, git commit hash: unknown
E1001 00:54:51.522797       1 server_status.go:117] Failed to get server status.
panic: collector has no descriptors

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc42003c880, 0xc4200f7c80, 0x1, 0x1)
	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:353 +0x92
github.com/prometheus/client_golang/prometheus.MustRegister(0xc4200f7c80, 0x1, 0x1)
	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:152 +0x53
main.registerCollector()
	/go/src/github.com/percona/mongodb_exporter/mongodb_exporter.go:186 +0x1cb
main.startWebServer()
	/go/src/github.com/percona/mongodb_exporter/mongodb_exporter.go:123 +0xc9
main.main()
	/go/src/github.com/percona/mongodb_exporter/mongodb_exporter.go:201 +0xce
```

**Comment by JohnnieFucker** [comment]
I have the same issue,is there any way to solve it?

**Comment by andremarinho** [comment]
> I have the same issue,is there any way to solve it?

I have the same problem, does anyone have the solution?
